@file:OptIn(ExperimentalMaterial3Api::class)

package s3605807.vamshinath.agricultureadvisoryapp.cropAdvisory

import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.spring
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

// ---------------------- DATA MODEL ----------------------

data class AdvisoryResult(
    val mistakes: List<String>,
    val recommendations: List<String>,
    val aiTips: List<String>,
    val score: Int
)

// ---------------------- LOGIC ENGINE ----------------------

fun generateAdvisory(crop: String, stage: String, soil: String): AdvisoryResult {

    val mistakes = mutableListOf<String>()
    val recommendations = mutableListOf<String>()
    val aiTips = mutableListOf<String>()

    var score = 10

    // 🌾 WHEAT
    if (crop == "Wheat") {

        if (soil == "Sandy") {
            mistakes.add("Sandy soil reduces nutrient retention")
            recommendations.add("Add compost or organic matter")
            aiTips.add("AI Suggestion: Use mulch to retain moisture")
            score -= 2
        }

        if (stage == "Flowering") {
            recommendations.add("Maintain consistent irrigation")
            aiTips.add("AI Suggestion: Monitor humidity to prevent fungal disease")
        }

        if (soil == "Clay") {
            recommendations.add("Ensure proper drainage")
        }

        aiTips.add("AI Suggestion: Use disease-resistant wheat varieties in UK climate")
    }

    // 🥔 POTATO
    if (crop == "Potato") {

        if (soil == "Clay") {
            mistakes.add("Clay soil may cause waterlogging")
            recommendations.add("Use raised beds for drainage")
            aiTips.add("AI Suggestion: Add sand to improve soil structure")
            score -= 2
        }

        if (stage == "Seedling") {
            recommendations.add("Avoid overwatering early stage")
        }

        aiTips.add("AI Suggestion: Monitor for blight during rainy UK weather")
    }

    // 🌍 GENERAL RULES
    if (soil == "Sandy") {
        recommendations.add("Increase watering frequency")
        score -= 1
    }

    if (soil == "Clay") {
        recommendations.add("Avoid over-irrigation")
    }

    return AdvisoryResult(mistakes, recommendations, aiTips, score.coerceAtLeast(0))
}

// ---------------------- UI ----------------------

@Composable
fun CropAdvisoryScreen(onBack: () -> Unit) {

    var crop by remember { mutableStateOf("") }
    var stage by remember { mutableStateOf("") }
    var soil by remember { mutableStateOf("") }

    val crops = listOf("Wheat", "Barley", "Potato", "Oilseed Rape", "Maize")
    val stages = listOf("Seedling", "Vegetative", "Flowering", "Maturity")
    val soils = listOf("Clay", "Sandy", "Loamy", "Silty")

//    val result = remember(crop, stage, soil) {
//        if (crop.isNotEmpty()) generateAdvisory(crop, stage, soil) else null
//    }

    var result by remember { mutableStateOf<AdvisoryResult?>(null) }
    var isGenerated by remember { mutableStateOf(false) }


    Column(modifier = Modifier.fillMaxSize()) {

        // 🌿 Gradient App Bar
        AdvisoryAppBar(onBack)

        LazyColumn(
            modifier = Modifier.fillMaxSize()
        ) {

            item {
                Column(modifier = Modifier.padding(16.dp)) {

                    DropdownField("Crop", Icons.Default.Eco, crops, crop) { crop = it }
                    Spacer(modifier = Modifier.height(12.dp))

                    DropdownField("Growth Stage", Icons.Default.TrendingUp, stages, stage) { stage = it }
                    Spacer(modifier = Modifier.height(12.dp))

                    DropdownField("Soil Type", Icons.Default.Landscape, soils, soil) { soil = it }

                    Spacer(modifier = Modifier.height(20.dp))

                    GenerateButton(
                        enabled = crop.isNotEmpty() && stage.isNotEmpty() && soil.isNotEmpty(),
                        onClick = {
                            result = generateAdvisory(crop, stage, soil)
                            isGenerated = true
                        }
                    )

                    Spacer(modifier = Modifier.height(20.dp))

                    if (isGenerated && result != null) {

                        PremiumAdvisoryCard(result!!)
//                        ScoreCard(result!!.score)
//                        Spacer(modifier = Modifier.height(16.dp))
//                        SmartAdvisoryCard(result!!)
                    }
                }
            }
        }
    }
}

@Composable
fun GenerateButton(
    enabled: Boolean,
    onClick: () -> Unit
) {

    val scale by animateFloatAsState(
        targetValue = if (enabled) 1f else 0.95f,
        animationSpec = spring()
    )

    Button(
        onClick = onClick,
        enabled = enabled,
        modifier = Modifier
            .fillMaxWidth()
            .scale(scale),
        shape = RoundedCornerShape(14.dp)
    ) {

        Icon(Icons.Default.AutoAwesome, contentDescription = null)

        Spacer(modifier = Modifier.width(8.dp))

        Text("Generate Advisory")
    }
}


@Composable
fun AdvisoryAppBar(onBack: () -> Unit) {

    Box(
        modifier = Modifier
            .fillMaxWidth()
            .background(
                Brush.horizontalGradient(
                    listOf(Color(0xFF2E7D32), Color(0xFF66BB6A))
                )
            )
            .padding(
                top = WindowInsets.statusBars.asPaddingValues().calculateTopPadding(),
                start = 16.dp,
                end = 16.dp,
                bottom = 16.dp
            )
    ) {

        Row(
            verticalAlignment = Alignment.CenterVertically
        ) {

            // 🔙 Back Button
            IconButton(onClick = onBack) {
                Icon(
                    imageVector = Icons.Default.ArrowBack,
                    contentDescription = null,
                    tint = Color.White
                )
            }

            Spacer(modifier = Modifier.width(8.dp))

            // 🌾 Title
            Text(
                text = "Crop Advisory",
                color = Color.White,
                fontSize = 20.sp,
                fontWeight = FontWeight.Bold
            )
        }
    }
}
// ---------------------- DROPDOWN ----------------------

@Composable
fun DropdownField(
    label: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    options: List<String>,
    selected: String,
    onSelected: (String) -> Unit
) {

    var expanded by remember { mutableStateOf(false) }

    ExposedDropdownMenuBox(expanded, { expanded = it }) {

        OutlinedTextField(
            value = selected,
            onValueChange = {},
            readOnly = true,
            label = { Text(label) },
            leadingIcon = { Icon(icon, null) },
            trailingIcon = {
                ExposedDropdownMenuDefaults.TrailingIcon(expanded)
            },
            modifier = Modifier.fillMaxWidth().menuAnchor()
        )

        ExposedDropdownMenu(expanded, { expanded = false }) {
            options.forEach {
                DropdownMenuItem(
                    text = { Text(it) },
                    onClick = {
                        onSelected(it)
                        expanded = false
                    }
                )
            }
        }
    }
}

// ---------------------- BUTTON ----------------------


// ---------------------- SCORE CARD ----------------------

@Composable
fun ScoreCard(score: Int) {

    val color = when {
        score >= 8 -> Color(0xFF4CAF50)
        score >= 5 -> Color(0xFFFF9800)
        else -> Color(0xFFF44336)
    }

    Card(
        shape = RoundedCornerShape(20.dp),
        colors = CardDefaults.cardColors(containerColor = color.copy(alpha = 0.1f))
    ) {

        Column(
            modifier = Modifier.padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {

            Text("Farming Score", fontWeight = FontWeight.Bold)

            Spacer(modifier = Modifier.height(8.dp))

            Text("$score / 10", fontSize = 28.sp, color = color)
        }
    }
}

// ---------------------- SMART CARD ----------------------

@Composable
fun SmartAdvisoryCard(result: AdvisoryResult) {

    Card(
        shape = RoundedCornerShape(20.dp),
        elevation = CardDefaults.cardElevation(6.dp)
    ) {

        Column(modifier = Modifier.padding(16.dp)) {

            Text("Smart Analysis", fontWeight = FontWeight.Bold)

            Spacer(modifier = Modifier.height(12.dp))

            if (result.mistakes.isNotEmpty()) {
                Text("❌ Mistakes", color = Color.Red)
                result.mistakes.forEach { Text("• $it") }
                Spacer(modifier = Modifier.height(8.dp))
            }

            Text("✅ Recommendations", color = Color(0xFF2E7D32))
            result.recommendations.forEach { Text("• $it") }

            Spacer(modifier = Modifier.height(8.dp))

            Text("🤖 AI Suggestions", color = Color(0xFF1976D2))
            result.aiTips.forEach { Text("• $it") }
        }
    }
}

@Composable
fun PremiumAdvisoryCard(result: AdvisoryResult) {

    val scoreColor = when {
        result.score >= 8 -> Color(0xFF4CAF50)
        result.score >= 5 -> Color(0xFFFF9800)
        else -> Color(0xFFF44336)
    }

    val gradient = Brush.verticalGradient(
        colors = listOf(
            scoreColor.copy(alpha = 0.15f),
            Color.White
        )
    )

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 8.dp),
        shape = RoundedCornerShape(24.dp),
        elevation = CardDefaults.cardElevation(8.dp)
    ) {

        Column(
            modifier = Modifier
                .background(gradient)
                .padding(16.dp)
        ) {

            // 🌾 Header + Score
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically
            ) {

                Column(modifier = Modifier.weight(1f)) {

                    Text(
                        text = "Farming Analysis",
                        fontWeight = FontWeight.Bold,
                        fontSize = 18.sp
                    )

                    Text(
                        text = "Based on your inputs",
                        fontSize = 12.sp,
                        color = Color.Gray
                    )
                }

                // 🎯 Score Badge
                Box(
                    modifier = Modifier
                        .clip(RoundedCornerShape(50))
                        .background(scoreColor)
                        .padding(horizontal = 16.dp, vertical = 8.dp)
                ) {
                    Text(
                        text = "${result.score}/10",
                        color = Color.White,
                        fontWeight = FontWeight.Bold
                    )
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            Divider()

            Spacer(modifier = Modifier.height(12.dp))

            // ❌ Mistakes
            if (result.mistakes.isNotEmpty()) {

                Text(
                    text = "❌ Mistakes",
                    color = Color(0xFFD32F2F),
                    fontWeight = FontWeight.Bold
                )

                Spacer(modifier = Modifier.height(6.dp))

                result.mistakes.forEach {
                    Text("• $it", fontSize = 14.sp)
                }

                Spacer(modifier = Modifier.height(12.dp))
            }

            // ✅ Recommendations
            Text(
                text = "✅ Recommendations",
                color = Color(0xFF2E7D32),
                fontWeight = FontWeight.Bold
            )

            Spacer(modifier = Modifier.height(6.dp))

            result.recommendations.forEach {
                Text("• $it", fontSize = 14.sp)
            }

            Spacer(modifier = Modifier.height(12.dp))

            // 🤖 AI Suggestions
            Text(
                text = "🤖 AI Suggestions",
                color = Color(0xFF1976D2),
                fontWeight = FontWeight.Bold
            )

            Spacer(modifier = Modifier.height(6.dp))

            result.aiTips.forEach {
                Text("• $it", fontSize = 14.sp)
            }
        }
    }
}